### ISSUE TITLE
Add AI Orchestrator VM 

### ISSUE THREAD

**Issue by tinova** [SovereignEdgeEU-COGNIT/cognit-ops-forge#10]
Now we have 

  *  OpenNebula front-end
  *  Provisioning engine
  * document architecture on README.
 
We need to add AI Orchestrator

**Comment by dann1** [comment]
Create an ansible role for the AI VM Deployment according to https://github.com/SovereignEdgeEU-COGNIT/ai-orchestrator?tab=readme-ov-file#ai-orchestrator
