### ISSUE TITLE
Add opsforge template schema

### ISSUE THREAD

**Issue by dann1** [SovereignEdgeEU-COGNIT/cognit-ops-forge#5]
The opsforge tool accepts a yaml formatted template that is used to create the infrastructure on AWS and to setup the frontend instance. The proposal is to add a schema for validation purposes in order to avoid unnecessary errors due to missing information or wrong value types.

**Comment by antalvrom** [comment]
Please @dann1 and @tinova please add this issue the Unit-Innovation and COGNIT projects so that it is visible for me as well :)

**Comment by dann1** [comment]
@antalvrom can you see the issues now ?
